spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auditdb?options=-c%20TimeZone=UTC
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration